In [5]:
import numpy as np
from   scipy.spatial   import distance_matrix

In [2]:
pos1 = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3]])
pos2 = np.array([[0,0,1], [0,0,2]])

In [6]:
def scipydm(pos1, pos2):
    return distance_matrix(pos1, pos2)

In [7]:
%timeit scipydm(pos1, pos2)

11.3 µs ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [65]:
def npdm(pos1, pos2, dimensions=None):
    """Calculate all possible distances between pos1 and pos2.
    If dimensions is not given, the returned value should be the same as 
    ``scipy.spatial.distance_matrix(pos1, pos2)``.
    
    Parameters
    ----------
    pos1 : numpy.ndarray
        array of shape ``(n, 3)``
    pos2 : numpy.ndarray
        array of shape ``(m, 3)``
    dimensions : numpy.ndarray or list, optional
        array or list in the format of [pbcx, pbcy, pbcz, 90, 90, 90].
        Periodic bounday condition will be taken into account if dimensions is provided.
        
    Retruns
    -------
    dis : numpy.ndarray
        a distance matrix of shape ``(n, m)``
    """
    
    dimensions = np.array(dimensions, dtype=np.float64)
    arr = np.repeat(pos1, len(pos2), axis=0) - np.tile(pos2, (len(pos1),1))

    # if any of the values of dimensions is 0, pbc will not be taken into account
    if np.all(dimensions):
        arr = arr - dimensions[0:3] * np.round(arr / dimensions[0:3])
    
    dis = np.sqrt(np.sum(arr**2, axis=1)).reshape(len(pos1), len(pos2))
        
    return dis

In [64]:
npdm(pos1, pos2, dimensions=[100,100,100])

array([[1.        , 2.        ],
       [1.41421356, 1.73205081],
       [3.        , 2.82842712],
       [4.69041576, 4.35889894]])

In [60]:
np.all(np.array([00, 100, 100], dtype=np.float64))

False

In [22]:
%timeit npdm(pos1, pos2)

11.4 µs ± 40.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
a = np.array([-1,0,1,2,3,4,5,6,7,8,9])
a - 5 * np.round(a/5)

array([-1.,  0.,  1.,  2., -2., -1.,  0.,  1.,  2., -2., -1.])

In [31]:
pos1 / np.array([1,2,3])

array([[0.        , 0.        , 0.        ],
       [1.        , 0.5       , 0.33333333],
       [2.        , 1.        , 0.66666667],
       [3.        , 1.5       , 1.        ]])

In [46]:
pos1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [50]:
np.random.rand(5, 3).dtype

dtype('float64')

In [51]:
np.array([10,20,30], dtype=np.float64).dtype

dtype('float64')